spring:
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/payment_service?replicaSet=rs0}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
