spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://payment-service-postgresql:5432/payment_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:payment_service}
    password: ${SPRING_DATASOURCE_PASSWORD:payment_service_secret}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
