server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: payment-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
